# Docker container with nginx server service up a Javascript Basil viewer

FROM node:latest as built

ENV DIR=/tmp/app

ARG BASIL_BRANCH=master

RUN apt-get update

RUN mkdir -p "$DIR"

ADD https://api.github.com/repos/herbal3d/basil/git/refs/heads/$BASIL_BRANCH basil-git-version.json
RUN cd "$DIR" \
    && git clone --depth 1 -b master --single-branch https://github.com/Herbal3d/basil.git

RUN cd "$DIR" \
    && cd basil/Basilts \
    && npm install \
    && npm run build

# ============================================================================
FROM nginx:latest

ENV DIR=/tmp/app

LABEL Description="Docker container for serving Basilts"

# These are not used except for debugging
# RUN apt-get update \
#     && apt-get install -y \
#         coreutils \
#         procps \
#         vim \
#     && rm -rf /var/lib/apt/lists/*

COPY --from=built $DIR/basil/Basilts/dist/ /usr/share/nginx/html
RUN cd /usr/share/nginx/html \
    && cp Entry.html index.html

EXPOSE 80/tcp

